language: "node_js"
node_js:
  - "node"
before_install:
  - find . -type f -name "*.md" ! -path "./README.md" -a ! -path "./SUMMARY.md"|xargs -i sed -ri '/^<extoc>/d;0,/^## /s/(^## .*)/\n<extoc><\/extoc>\n\n\1/' '{}'
install:
  - "npm install -g gitbook@3.2.3"
  - "npm install -g gitbook-cli@2.3.2"
branches:
  only:
    - master
env:
  global:
    - GH_REF: github.com/KunBlog/blog.git
#sudo: false
script:
  - bash summary_create.sh
  - travis_wait 100 bash deploy.sh
